Refactor code
moip/rcurtain pull request #7
Opened 2018-04-07 03:04 UTC by lucasqueiroz

Follow ruby style guide
Add methods to retrieve feature information (#6)

2018-04-09 14:13 UTC, carlosmenezes commented on lib/rcurtain/curtain.rb
> +      return false if users.empty?
`return false if users.nil? || users.empty?`

pra evitar nullpointer... ou se incluir a gem activesupport pode usar `users.blank?`

2018-04-09 14:14 UTC, lucasqueiroz commented on lib/rcurtain/curtain.rb
> +      return false if users.empty?
Boa... Acho que o melhor seria fazer o `return false if users.nil? || users.empty?`, pq adicionar a gem só para isso acho que não vale a pena.

2018-04-09 14:45 UTC, rfocosi requested changes

2018-04-09 14:45 UTC, rfocosi commented on lib/rcurtain/curtain.rb
> +      users.all? { |user| allowed_users.include?(user) }
Muda pra:
`users.present? && users.all? { |user| allowed_users.include?(user) }`
E remove aquele `return`

2018-04-09 14:50 UTC, rfocosi requested changes

2018-04-09 14:50 UTC, rfocosi commented on lib/rcurtain/feature.rb
> +    def add_users(feature_name, users)
Tanto `users` quanto `percentage` são features.
Deveria renomear os métodos para `add`, `remove` e `update` simplesmente.
E os métodos `users` e `percentage` para `get_array` e `get_number` (porcentagem é `float`)

2018-04-09 16:00 UTC, lucasqueiroz commented on lib/rcurtain/feature.rb
> +    def add_users(feature_name, users)
A porcentagem, no RCurtain, segundo o @gabrielqueiroz, é integer :disappointed:
Vou renomear os métodos

2018-04-09 16:01 UTC, lucasqueiroz commented on lib/rcurtain/feature.rb
> +    def add_users(feature_name, users)
O correto não seria `array` e `number`?

2018-04-09 16:31 UTC, gabrielqueiroz commented on rcurtain.gemspec
> +  s.authors     = ['Danillo Souza', 'Gabriel Queiroz', 'Guilherme Sipoloni']
Adiciona o seu nome nos autores.

2018-04-09 16:31 UTC, gabrielqueiroz commented on rcurtain.gemspec
> +  s.email       = ['danillo.souza@moip.com.br', 'gabriel.queiroz@moip.com.br',
E o seu email.

2018-04-09 16:32 UTC, gabrielqueiroz commented on rcurtain.gemspec
> +                   'guilehrme.sipoloni@moip.com.br']
Aproveita para corrigir o e-mail do @GuiSipoloni que esta errado 😂

2018-04-09 16:35 UTC, gabrielqueiroz commented on spec/lib/curtain_spec.rb
> +        before do
**DRY**
Você pode deixar esse trecho do before dentro do contexto maior ('when percentage is fully closed'). Assim não precisa repetir ele em todos os testes d o mesmo contexto.

2018-04-09 16:58 UTC, rfocosi commented on lib/rcurtain/feature.rb
> +    def add_users(feature_name, users)
Isso

2018-04-26 15:07 UTC, rfocosi approved these changes

2018-07-11 00:21 UTC, gabrielqueiroz commented on lib/rcurtain/curtain.rb
> +    rescue Redis::CannotConnectError
Acho que podemos mover esse `rescue Redis::CannotConnectError` pro método `opened?`. Assim não precisaria repetir ele no percentage_allowed? também.

2018-07-11 22:26 UTC, CuriousFurBytes commented
I'm closing this Pull Request because I'm working on the refactor in a fork.

2018-07-11 22:26 UTC, closed without merging